#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Embed the 9 timestamped SPIR-V shader modules into a C++ header.

The generated header (``_cpp/render/shaders_spv.h``) defines one
``static const uint32_t kSpv_<NAME>[]`` array per stage. The Vulkan
renderer includes this header and feeds the arrays directly to
``vkCreateShaderModule`` -- no runtime file loading required.

Run after ``compile.sh``:

    python3 ludus_renderer/shaders/nv_to_ext.py
    bash    ludus_renderer/shaders/compile.sh
    python3 ludus_renderer/shaders/embed_spv.py
"""

from __future__ import annotations

import os
import struct
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_HEADER = os.path.normpath(os.path.join(
    SCRIPT_DIR, "..", "_cpp", "render", "shaders_spv.h"
))

SPV_FILES = [
    ("ts_polyline_task", "ts_polyline.task.spv"),
    ("ts_polyline_mesh", "ts_polyline.mesh.spv"),
    ("ts_polyline_frag", "ts_polyline.frag.spv"),
    ("ts_polygon_task",  "ts_polygon.task.spv"),
    ("ts_polygon_mesh",  "ts_polygon.mesh.spv"),
    ("ts_polygon_frag",  "ts_polygon.frag.spv"),
    ("ts_obstacle_task", "ts_obstacle.task.spv"),
    ("ts_obstacle_mesh", "ts_obstacle.mesh.spv"),
    ("ts_obstacle_frag", "ts_obstacle.frag.spv"),
]

HEADER_TOP = """\
// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// AUTOGENERATED by ludus_renderer/shaders/embed_spv.py
// DO NOT EDIT BY HAND. Regenerate with:
//   python3 ludus_renderer/shaders/nv_to_ext.py
//   bash    ludus_renderer/shaders/compile.sh
//   python3 ludus_renderer/shaders/embed_spv.py

#pragma once
#include <cstdint>

"""


def emit_array(name: str, data: bytes, out) -> int:
    if len(data) % 4 != 0:
        raise RuntimeError(f"{name}: SPIR-V length {len(data)} not 4-byte aligned")
    words = struct.unpack(f"<{len(data) // 4}I", data)
    out.write(f"static const uint32_t kSpv_{name}[] = {{\n")
    for i in range(0, len(words), 8):
        chunk = ", ".join(f"0x{w:08x}u" for w in words[i:i + 8])
        out.write(f"    {chunk},\n")
    out.write("};\n\n")
    return len(words)


def main() -> int:
    missing = [fn for _, fn in SPV_FILES
               if not os.path.exists(os.path.join(SCRIPT_DIR, fn))]
    if missing:
        print("Missing .spv files (run compile.sh first):", file=sys.stderr)
        for m in missing:
            print(f"  {m}", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUT_HEADER), exist_ok=True)
    with open(OUT_HEADER, "w") as out:
        out.write(HEADER_TOP)
        total_words = 0
        for var, fn in SPV_FILES:
            with open(os.path.join(SCRIPT_DIR, fn), "rb") as f:
                data = f.read()
            words = emit_array(var, data, out)
            total_words += words
            print(f"  {fn:30s} -> kSpv_{var:20s} ({words * 4} bytes)")
        out.write(f"// total embedded SPIR-V: {total_words * 4} bytes\n")
    print(f"Wrote {OUT_HEADER}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
